### ISSUE TITLE
Clockratepr set to normal, but samples as fixed

### ISSUE THREAD

**Issue by ivanlfm** [NBISweden/MrBayes#133] opened 2019-10-18 14:44 UTC
Hello,

I am trying to run a calibrated, tip-dated phylogeny using morphology and sequences in MrBayes 3.2.7a on Windows 7 64 bits that includes eight fossils as terminals. The ages of the fossils are given in millions of years. Treeagepr is also constrained by fossil information using a uniform distribution.

I specified a quite permissive normal distribution for the clockratepr [prset clockratepr = normal(0.5,0.2)], so that the ages of the branches are given exclusively by the fossils.  The model appears to be specified correctly:

        _23 --  Parameter  = Clockrate{all}
               Type       = Base rate of clock
               Prior      = Normal(0.500000,0.200000)
               The clock rate varies according to an independent gamma (white noise) model
               Partitions = All_

However, the output shows that the clockrate parameter is equal to 0.5 in all generations (i.e. Tracer shows this parameter has mean 0.5 and stdev of 0 in all sampled generations). It seems that the clockrate parameter is being sampled as "fixed" instead of "normal". What could be the cause of this? Using a different prior for clockratepr (i.e. lognormal) results in this parameter being sampled normally according to the prior distribution, so I suspect the issue is with the "normal" distribution only.

The end of my MrBayes block is available below (please note I am using a non-calibrated starting topology to improve convergence).

Many thanks in advance for any input.
Best regards,
Ivan

```
			calibrate
			Antilloides_didicostae = uniform(15,20)
			Chimerarachne_yingi = uniform(98,99)
			Palaeothele_montceauensis = uniform(299,304)
			Rosamygale_grauvogeli = uniform(242,247)
			Seppo_koponeni = uniform(173,183)
			Zamilia_quattuormammillae = uniform(98,99)
			Eoplectreurys_gertschi = uniform(164,175)
			Montsecarachne_amicorum = uniform(125,129);

		outgroup Chimerarachne_yingi;
		prset topologypr = constraints (Araneae, Opisthothelae, Mygalomorphae, Araneomorphae, haplogynes, HypFil, KukFilistata, Synspermiata, ScytodLTC, LTC, CySpigot, AustrLep, Austrochiloidea, PalpEntelegynae, Entelegynae);

		prset nodeagepr = calibrated;
		prset brlenspr = clock:uniform;
		prset clockvarpr=igr;
		prset igrvarpr = exponential(10);
		prset clockratepr = normal(0.5,0.2);
		prset treeagepr = uniform(299,435);
		
		startvals Tau{all}= startingtree;
		
		mcmcp ngen= 50000000 relburnin=yes burninfrac=0.25 printfreq=5000 samplefreq=5000 nchains=4 savebrlens=yes;
		mcmc;
		sumt;
```

**Comment by ivanlfm** [comment] 2019-10-18 15:02
Some additional information:

**How may we reproduce this bug?**

I can provide my input file upon request. 

**Would you be able to compile and run MrBayes to test fixes to this bug?**

No, sorry.

**What is the environment that you run MrBayes in?**

```
Version 

MrBayes 3.2.7a

Features:
Host type: x86_64-w64-mingw32 (CPU: x86_64)
Compiler: gnu 7.3.0
```

I also encountered the same problem while running the analysis on Cipres Science Gateway.

**Comment by zhangchicool** [comment] 2020-06-16 02:27
I tried with my own datasets but cannot reproduce this issue. I wonder there might be other commands used that are not compatible with the clockratepr or normal distribution, but has no clue. Please provide a complete example that the phenomenon can be reproduced.

**Comment by ivanlfm** [comment] 2020-06-16 02:55
Hello, thank you so much for looking into this. Attached is the input file that generated the issue. 

Also I am attaching a screenshot of the Tracer graphic showing that the parameter is being sampled as fixed.Let me know if you have any further qustions.

I have finally worked around it by using an exponential prior on the clock rate, but I am still curious to see if there is a solution.

Again, thank you so much.

**Comment by zhangchicool** [comment] 2020-06-16 02:58
Attachment cannot be found...

**Comment by ivanlfm** [comment] 2020-06-16 15:25
Here they are.
![normal-clock-rate](https://user-images.githubusercontent.com/56691122/84794345-82bf8480-afcc-11ea-9278-7727add9df48.jpg)

**Comment by ivanlfm** [comment] 2020-06-16 15:26
[infile.txt](https://github.com/NBISweden/MrBayes/files/4787465/infile.txt)

**Comment by ivanlfm** [comment] 2020-06-16 15:33
Please notice now I am also getting another error because of treeagepr on line 353:

		prset treeagepr = uniform(299,435);

The run fails and says the following, even though "uniform" is a valid argument for treeagepr according to MrBayes command reference:

      No valid match for argument "uniform"
      Invalid Treeagepr argument
      Error when setting parameter "Treeagepr" (2)
      The error occurred when reading char. 21 on line 353

I commented the line for the file to be processed. The issue of the clockrate being sampled as fixed still happens.

**Comment by zhangchicool** [comment] 2020-06-17 13:49
Thanks. Now I understand the problem. It is due to an unnecessary checking of maximum branch length that can cause the move of clock rate to be always rejected. It is fixed in the latest code.

The initial value of the clock rate is the prior mean (0.5 in this case). Obviously,  this prior is a poor one as the mean value is too large. A better prior, which is also a workaround, would be normal(0.01, 0.2) or exp(100), with a smaller mean.

The uniform prior for treeageprior works perfectly for me, I do not see this error message.

**Closed as completed by zhangchicool** 2020-06-17 13:49 UTC

**Comment by ivanlfm** [comment] 2020-06-17 14:12
Thank you!
