### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [NBISweden/MrBayes#257] opened 2021-11-27 15:10 UTC
I would like to point out that identifiers like “[`__BAYES_H__`](https://github.com/NBISweden/MrBayes/blob/ea2712ec4c8f60efacf9c1cc00f11c2f40d3e577/src/bayes.h#L1 "Update candidate")” and “[`__MCMC_H__`](https://github.com/NBISweden/MrBayes/blob/8a53ac7029cd3638e564fb2456cc3315bafbf874/src/mcmc.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by andkaha** [comment] 2023-10-19 07:48
As the project's preprocessor identifiers do not comply with the C99 standard in starting with `__` (denoting identifiers reserved by the implementation), we will ensure that these are changed by simply removing the `__` prefix.

Note, though, that we don't use C++ and that the code generally does not adhere to C++ coding standards (which is what the issue linked to).

**Comment by elfring** [comment] 2023-10-19 08:13
>…, we will ensure that these are changed by simply removing the `__` prefix.

Both programming languages have got rules for the reserved name space.
:thought_balloon: I suggest to [reconsider the usage of double underscores at more source code places](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by andkaha** [comment] 2023-10-19 09:15
> > …, we will ensure that these are changed by simply removing the `__` prefix.
> 
> Both programming languages have got rules for the reserved name space. 💭 I suggest to [reconsider the usage of double underscores at more source code places](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797).

We are aware that C has reserved identifiers (see section 7.1.3 of the C standard). I'm sorry if my previous comment was sloppy and didn't indicate that all double underscores will be deleted from preprocessor macro identifiers. However, unless you have examples of actual clashes with identifiers defined by a compiler which stops this software from functioning correctly, we will not go through the code to change other types of identifiers than preprocessor macros.

**Comment by elfring** [comment] 2023-10-19 09:20
Would you like to take [descriptions for undefined behavior](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Documentation for C++ identifiers") better into account? :thinking:

**Comment by andkaha** [comment] 2023-10-19 09:50
> Would you like to take [descriptions for undefined behavior](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations) better into account? 🤔

Yes, definitely, if you can show a C99 compiler that defines an identifier that we use in this project. I will change the preprocessor identifiers, as they have been on my mind for a long time anyway.  Changing other identifiers requires too much effort for not enough gain unless, as I have mentioned, you can show that there are actual bugs that would be fixed on some platforms (where this utility is used) by renaming specific identifiers.

Note that MrBayes (this project) is in maintenance mode, which means active development is extremely slow and we concentrate primarily on correcting serious issues that stop users from conducting their research. 

In effect, I'm asking you to provide more of a basis for the changes that you request, other than pure language standard technicalities. I'm not saying these are unimportant, but taking into account that our allocated time with this project is limited, we need to carefully pick the issues that we think provide a tangible benefit to our users.

**Comment by elfring** [comment] 2023-10-19 12:48
>…, if you can show a C99 compiler that defines an identifier that we use in this project.

:thought_balloon: Please reconsider such information a bit more.


>In effect, I'm asking you to provide more of a basis for the changes that you request, other than pure language standard technicalities.

:crystal_ball: Will development interests grow for [the avoidance of undefined behavior](https://wiki.sei.cmu.edu/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Documentation") (besides affected include guards)?

**Comment by andkaha** [comment] 2023-10-19 13:56
> > …, if you can show a C99 compiler that defines an identifier that we use in this project.
> 
> 💭 Please reconsider such information a bit more.

Yes, definitely. You just need to provide an example where an identifier clashes with something that is predefined by a compiler, and we will fix that.

> 
> > In effect, I'm asking you to provide more of a basis for the changes that you request, other than pure language standard technicalities.
> 
> 🔮 Will development interests grow for [the avoidance of undefined behavior](https://wiki.sei.cmu.edu/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106) (besides affected include guards)?
 
Absolutely, if you can show that this affects the output of the code. As previously mentioned, this project is in a stage where the main efforts are spent on fixing issues that are demonstratedly problematic. Theoretical technicalities would have to be substantiated to be worth allocating time to.

I consider most of my time spent working on MrBayes this week used up in this dialogue with you. I also notice that you have submitted another issue I will address shortly. I will consider the include-guards as promised (probably next week), but we will not audit the code for other identifiers that may have ill-advised names, simply because no issues relating to this have been reported.  If you want to report such an issue, please do so, but also submit a testable example showing that the output of the program is incorrect and that changing the identifiers' names corrects the issue.  This would be beneficial.

I would also suggest that you respond with slightly more than single sentences, emojis and links, or I will assume that you're a chatbot and will close your issues, current and future, without further investigation.

**Comment by elfring** [comment] 2023-10-19 14:18
>Theoretical technicalities would have to be substantiated to be worth allocating time to.

I hope that  development interests will grow also according to secure programming guidelines.


>I consider most of my time spent working on MrBayes this week used up in this dialogue with you.

I got the impression that your feedback would indicate a need for additional persuasion efforts.


>I would also suggest that you respond with slightly more than single sentences, emojis and links, or I will assume that you're a chatbot and will close your issues, current and future, without further investigation.

I find it interesting that you got into the mood somehow to interpret some of the presented information in such a direction.
I dare to point recurring programming mistakes out since years.

**Comment by andkaha** [comment] 2023-10-19 15:09
> > Theoretical technicalities would have to be substantiated to be worth allocating time to.
> 
> I hope that development interests will grow also according to secure programming guidelines.

Defensive programming, adherence to standards, and knowledge of programming guidelines and best practices are all well and good, but also consider the age of this project along with the fact that it was initiated in an environment where getting computational results trumps the security aspects of the code.


> > I consider most of my time spent working on MrBayes this week used up in this dialogue with you.
> 
> I got the impression that your feedback would indicate a need for additional persuasion efforts.

On the contrary, I'm just doing my best to be civil. I could do as some other software maintainers do and simply close issues that "I don't like", but I don't really believe in that model. What would persuade me would be an issue that is more than a pointer to a language standard or some coding guidelines.  We are aware that some of the code is not on par with, say, the quality of the Linux kernel code base, and we are also aware of some of the changes that would be necessary to implement to fix this. The issue is time and money (this is not a hobbyist project). 

> 
> > I would also suggest that you respond with slightly more than single sentences, emojis and links, or I will assume that you're a chatbot and will close your issues, current and future, without further investigation.
> 
> I find it interesting that you got into the mood somehow to interpret some of the presented information in such a direction. I dare to point recurring programming mistakes out since years.

My apologies; it's just a nod to the fact that it's easy for an AI to spot patterns that indicate bad programming habits, but it's more difficult for it to correct them safely. Or so I imagine; it's mostly true for humans, at least. Responding in short bursts, with emojis picked using the context of the text, with links to preselected pieces of information, is also typical of how I imagine an AI would interact. Add to this that you have not even attempted to give examples of corrected code, but have only pointed to existing pieces of information, and I may be forgiven for making assumptions.

Don't think for a second that I'm unaware that the code would need a proper audit, refactoring (including serious code deduplication), and general love and care. But, as mentioned _a few times_ by now, this will unlikely happen within the foreseeable future given our current level of engagement with this project. In the meantime, we try to address the more hands-on issues submitted by our users (even though we fall behind there too, mostly due to some of us being busier than others).

**Comment by elfring** [comment] 2023-10-19 15:40
>…, but I don't really believe in that model.

Thanks for such feedback.


>Add to this that you have not even attempted to give examples of corrected code,

Known information sources contain corresponding advices.


>… but have only pointed to existing pieces of information, …

Further development tools can help to achieve desirable source code adjustments, can't they?

**Comment by andkaha** [comment] 2023-10-19 16:58
> > …, but I don't really believe in that model.
> 
> Thanks for such feedback.
> 
> > Add to this that you have not even attempted to give examples of corrected code,
> 
> Known information sources contain corresponding advice.
> 

No, a standard such as C99 describes a language. It says very little about how to write or rewrite an existing application to do any particular thing. Compare how a literary style guide, dictionary, and phrase book says nothing about how to write a novel.

The word I should have used is "contribution", of which there is none in this issue, not even of a failure.

> > … but have only pointed to existing pieces of information, …
> 
> Further development tools can help to achieve desirable source code adjustments, can't they?

This question seems to be outside the scope of a Github issue, don't you agree? It would fit better in a developer's blog.

**Closed as completed** 2023-10-20 07:51 UTC

**Comment by nylander** [comment] 2023-10-20 07:53
This issue turned into a general discussion. Performing the proposed changes is not a current priority.
