### ISSUE TITLE
Changing number of chain or run gets WARNING: (re)allocation of zero size attempted

### ISSUE THREAD

**Issue by zhangchicool** [NBISweden/MrBayes#28] opened 2016-07-18 07:42 UTC
when changing the number of runs (from 2(default) to 1):
      WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.

when changing the number of chains (from 4(default) to 1):
      WARNING: Allocation of zero size attempted. This is probably a bug; problems may follow.

**Comment by kusalananda** [comment] 2016-07-18 07:45
How do I reproduce this?

**Comment by zhangchicool** [comment] 2016-07-18 08:15
Sorry I forgot to mention. You can use the following commands:
```
exe primates.nex [a file in the examples folder]
mcmcp nrun=1 nchain=2
```
to reproduce this :)

**Comment by kusalananda** [comment] 2016-08-01 11:55
I can reproduce this.

**Comment by kusalananda** [comment] 2016-08-15 09:42
When you do

```
exe primates.nex
mcmcp nrun=1 nchain=2
```

you get

```
WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
   WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
   Setting number of runs to 1
   WARNING: Allocation of zero size attempted. This is probably a bug; problems may
follow.
   Setting number of chains to 2
   Setting chain output file names to "primates.nex.<p/t>"
   Successfully set chain parameters
```

- The first warning comes from `intValues = (int *) SafeRealloc ((void *) intValues, intValsRowSize * 2 * numGlobalChains * sizeof (int));` when `intValsRowSize == 0` (`model.c` line 1508, in `ChangeNumRuns()`).
- The second warning comes from `moves[i]->tuningParam[0] = (MrBFlt *) SafeRealloc ((void *) moves[i]->tuningParam[0], (size_t)numGlobalChains * (size_t)(mvt->numTuningParams) * sizeof (MrBFlt));` when `mvt->numTuningParams == 0` (`model.c`, line 1576, in `ChangeNumRuns()`).
- The third warning comes from `cppEventParams = (Param *) SafeCalloc (nCppEventParams, sizeof(Param));` with `nCppEventParams == 0` (`model.c`, line 1123, in `ChangeNumChains()`).

**Comment by andkaha** [comment] 2020-07-04 06:57
Closing this as it's a duplicate and since it has been fixed (can't reproduce it any longer).

**Closed by andkaha** 2020-07-04 06:57 UTC
Labels: bug, duplicate
