### ISSUE TITLE
Warnings in setting nruns=1

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#70] opened 2018-07-10 16:29 UTC
MrBayes 3.2.7 develop branch, Latest commit 0fdbddf (compiled and run on Linux):

Using `mcmcp` (or `mcmc`) to set  `nruns=1` gives a warning: "Reallocation of zero size attempted. This is probably a bug. Problems may follow."

To reproduce:

`
MrBayes > exe primates.nex
MrBayes > mcmcp nruns=1

   WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
   WARNING: Reallocation of zero size attempted. This is probably a bug. Problems may follow.
   Setting number of runs to 1
   Setting chain output file names to "primates.nex.<p/t>"
   Successfully set chain parameters
`

**Comment by nylander** [comment] 2018-10-02 08:35
Same issue as #28

**Comment by tbauma1** [comment] 2019-07-08 21:01
Was this issue resolved?  I received the same error today when changing nruns.

**Comment by nylander** [comment] 2019-07-15 10:17
No, not yet resolved. The "Problems" mentioned by the warning message, however, does not effect the output results.

**Comment by andkaha** [comment] 2019-08-22 10:15
* The 1st warning occurs because `intValsRowSize` is zero at line 1530 of `model.c`.
* The 2nd warning occurs because `mtv->numTuningParams` is zero at line 1599 of `model.c`.

I can't say whether these zeros are to be expected or not, but I have commented out the warning as reallocating with a zero size is not a problem _in general_.

**Comment by andkaha** [comment] 2019-08-22 10:35
The code on the `develop` branch will no longer issue this particular warning. I'm leaving this issue open for @nylander or @ronquist to close after review.

**Comment by terrycojones** [comment] 2019-10-04 10:29
I'm running `pre-3.2.7` and have just run into this. I only found the warning message because my two `mb` runs both seem to have finished cleanly but there is no `.con.tre` file left in the run directory. I know very little about `mb`, sorry!, but in runs I've done for other people I usually just send them the `*.con.tre` file.  Here's the file I am giving to `mb`:

```
exec "Protein_alignment_N-short-names.nex";                  
outgroup 60;                  
lset rates=gamma nst=6;       
prset aamodel=fixed(wag);     
set seed=28152 quitonerror=no;                               
set autoclose=yes nowarn=yes usebeagle=yes beagleresource=99 beagledevice=gpu beaglesse=no beagleprecision=single;        
mcmc ngen=10000000 temp=0.2 samplefreq=200 nruns=4 nchains=4 mcmcdiagn=yes;                                               
```

The `nruns` and `nchains` values are ones I have used in the past with `pre-3.2.7` with no problem.

Could this warning message be related to no `*.con.tre` file being created, or would that be a different issue?

Thanks!

**Comment by nylander** [comment] 2019-10-04 10:35
Dear terrycojones,
no, the missing `*.con.tre` is due to the lack of a `sumt` command - which summarizes the tree sample (`*.t`) and calculates a consensus tree.
/Johan

**Comment by terrycojones** [comment] 2019-10-04 11:35
@nylander Ah....! I guess I must have run that manually last time. I do at least remember the command name. Thank you.

**Comment by ronquist** [comment] 2020-02-01 19:03
The "bug", which causes this problem was removed some time ago. A zero-size reallocation is in itself unproblematic, as Andreas notes. The problem is that such a reallocation may be a symptom of other problems. I have uncommented the warning text, so it will now again be printed if a zero-size reallocation is attempted. In this particular case, however, this will not happen.

**Comment by andkaha** [comment] 2020-02-03 11:59
PR #153 (now merged) resolves this.

**Closed by andkaha** 2020-02-03 11:59 UTC
Labels: bug, duplicate
