### ISSUE TITLE
MPI compilation issue: configure: error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by 473021677** [NBISweden/MrBayes#103] opened 2019-04-22 17:26 UTC
Description:
Compiling MrBayes failed on Centos. Trying to reproduce, and the same problem shows.

Details:
   I intend to conduct the Bayesian phylogenetic analysis using MrBayes. I have downloaded it using the command "git clone --depth=1 https://github.com/NBISweden/MrBayes.git". I am working on the Linux system with the centos Linux distribution. Then I want to compile it on the Linux system with an mpi compiler in addition to autoconf and make. I have tried to compile it by typing the command "env MPICC="/usr/local/bin/mpicc" ./configure --with-mpi". But it failed. The compilation process looks like this:

The compilation process:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for pdflatex... /usr/bin/pdflatex
checking for bibtex... /usr/bin/bibtex
checking for style of include used by make... GNU
checking whether to compile using MPI... yes
checking for gcc... /data/data/yuanyang/softwares/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/data/data/yuanyang/softwares/MrBayes':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

I don't know how this happen and would it be possible for you to help me?

Sincerely,
Yuan

**Comment by andkaha** [comment] 2019-04-23 09:19
Hi Yuan,

Is `/usr/local/bin` in your `$PATH`? What happens if you _only_ use `--with-mpi`? Or if you use `--with-mpi=/usr/local`?

Would you be able to share the `config.log` file that is generated from a failed run of the `configure` script, or at least the part of it that mentions the error (it will not be at the very end of the file, but a bit up from the end)?

**Comment by nannabarnkob** [comment] 2019-04-24 16:29
Hi both 

I had the same problem today. I solved it by updating Xcode Command Line Tools with ` xcode-select --install ` as suggested [here](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-mojave-update-xcrun-error-invalid-active-devel). 

The config.log file had something like the following line: 
` xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun` which gave it away. I am working on mac though, so I don't know if it applies to you. 

Maybe it helps :) 
Nanna

**Comment by andkaha** [comment] 2019-04-24 16:39
@nannabarnkob No, it would unfortunately not apply to compiling MrBayes on their CentOS system.

I can also mention another possible thing to try (if that compilation error does not go away using my suggested tweaks), which is to install MrBayes through Homebrew (macOS) or Linuxbrew (the same thing, but for Linux).  I just recently added instructions for how to do this in the `INSTALL` document here: https://github.com/NBISweden/MrBayes/blob/develop/INSTALL

**Comment by nylander** [comment] 2019-04-25 13:24
Dear Yuan,
we did run mb successfully on Cent OS 7 using the commands described in this document:
https://github.com/NBISweden/MrBayes/blob/testing/beagle/centos.7.md
Could you please try to see if they work for you?
Cheers
Johan

**Comment by andkaha** [comment] 2019-05-09 13:27
We're closing this issue as the problem is not reproducible. We're able to build MrBayes for CentOS 7 with MPI functionality.

If you (@473021677) can provide further information, e.g. the `config.log` file, then we're happy to reopen the issue.

**Closed as completed by andkaha** 2019-05-09 13:27 UTC
Labels: MPI-related

**Comment by 473021677** [comment] 2019-05-12 00:17
Thanks for your help very much. I have solved this problem. Thanks again!
 
 
------------------ Original ------------------

**Comment by zhouzhendiao** [comment] 2020-02-09 12:15
> We're closing this issue as the problem is not reproducible. We're able to build MrBayes for CentOS 7 with MPI functionality.
> 
> If you (@473021677) can provide further information, e.g. the `config.log` file, then we're happy to reopen the issue.

Hi kusalananda:
I have the same problem in my WSL2(Ubuntu 18.04 ). 
I installed MPI in `/usr/local/bin` and configure like below:

```
 env MPICC="/usr/local/bin/mpicc" ./configure --with-mpi
```

the ouput echoed error:
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for pdflatex... no
checking for bibtex... no
checking for latexmk... no
configure: WARNING: pdflatex and/or bibtex is missing, documentation will not be rebuilt
checking for style of include used by make... GNU
checking whether to compile using MPI... yes
checking for gcc... /usr/local/bin/mpicc
checking whether the C compiler works... no
configure: error: in `/mnt/c/software/MrBayes':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
The `config.log`:
```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by MrBayes configure 3.2.7a, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --with-mpi=/usr/local

## --------- ##
## Platform. ##
## --------- ##

hostname = DESKTOP-0EHBNA1
uname -m = x86_64
uname -r = 4.4.0-18362-Microsoft
uname -s = Linux
uname -v = #476-Microsoft Fri Nov 01 16:53:00 PST 2019

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/simon/.local/bin
PATH: /home/simon/anaconda3/bin
PATH: /home/simon/anaconda3/condabin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games
PATH: /mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc
PATH: /mnt/c/software/MEGA6
PATH: /mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath
PATH: /mnt/c/Program Files (x86)/NetSarang/Xshell 6
PATH: /mnt/c/Program Files (x86)/NetSarang/Xftp 6
PATH: /mnt/c/WINDOWS/system32
PATH: /mnt/c/WINDOWS
PATH: /mnt/c/WINDOWS/System32/Wbem
PATH: /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0
PATH: /mnt/c/WINDOWS/System32/OpenSSH
PATH: /mnt/c/Program Files/MEGA-X
PATH: /mnt/c/Users/simon/AppData/Local/Microsoft/WindowsApps
PATH: /mnt/c/Users/simon/AppData/Local/BypassRuntm
PATH: /mnt/c/Users/simon/AppData/Local/Microsoft/WindowsApps
PATH: /mnt/c/ProgramData/simon/GitHubDesktop/bin
PATH: /mnt/c/Users/simon/AppData/Local/GitHubDesktop/bin
PATH: /mnt/c/Program Files/JetBrains/PyCharm Community Edition 2019.3/bin
PATH: /mnt/c/Program Files/JetBrains/PyCharm Professional Edition with Anaconda plugin 2019.3/bin
PATH: /snap/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2502: checking for a BSD-compatible install
configure:2570: result: /usr/bin/install -c
configure:2581: checking whether build environment is sane
configure:2636: result: yes
configure:2787: checking for a thread-safe mkdir -p
configure:2826: result: /bin/mkdir -p
configure:2833: checking for gawk
configure:2849: found /usr/bin/gawk
configure:2860: result: gawk
configure:2871: checking whether make sets $(MAKE)
configure:2893: result: yes
configure:2922: checking whether make supports nested variables
configure:2939: result: yes
configure:3066: checking whether to enable maintainer-specific portions of Makefiles
configure:3075: result: no
configure:3097: checking build system type
configure:3111: result: x86_64-unknown-linux-gnu
configure:3131: checking host system type
configure:3144: result: x86_64-unknown-linux-gnu
configure:3331: checking for pkg-config
configure:3349: found /usr/bin/pkg-config
configure:3361: result: /usr/bin/pkg-config
configure:3386: checking pkg-config is at least version 0.9.0
configure:3389: result: yes
configure:3413: checking for pdflatex
configure:3446: result: no
configure:3453: checking for bibtex
configure:3486: result: no
configure:3493: checking for latexmk
configure:3526: result: no
configure:3546: WARNING: pdflatex and/or bibtex is missing, documentation will not be rebuilt
configure:3573: checking for style of include used by make
configure:3601: result: GNU
configure:3627: checking whether to compile using MPI
configure:3634: result: yes
configure:3791: checking for gcc
configure:3818: result: /usr/local/bin/mpicc
configure:4047: checking for C compiler version
configure:4056: /usr/local/bin/mpicc --version >&5
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
configure:4067: $? = 127
configure:4056: /usr/local/bin/mpicc -v >&5
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
configure:4067: $? = 127
configure:4056: /usr/local/bin/mpicc -V >&5
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
configure:4067: $? = 127
configure:4056: /usr/local/bin/mpicc -qversion >&5
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
configure:4067: $? = 127
configure:4087: checking whether the C compiler works
configure:4109: /usr/local/bin/mpicc -O3 -DNDEBUG -std=c99 -pedantic    conftest.c  >&5
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
configure:4113: $? = 127
configure:4151: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "MrBayes"
| #define PACKAGE_TARNAME "mrbayes"
| #define PACKAGE_VERSION "3.2.7a"
| #define PACKAGE_STRING "MrBayes 3.2.7a"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "mrbayes"
| #define VERSION "3.2.7a"
| #define HOST_TYPE "x86_64-unknown-linux-gnu"
| #define HOST_CPU "x86_64"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4156: error: in `/mnt/c/software/MrBayes':
configure:4158: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_BEAGLE_CFLAGS_set=
ac_cv_env_BEAGLE_CFLAGS_value=
ac_cv_env_BEAGLE_LIBS_set=
ac_cv_env_BEAGLE_LIBS_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MPICC_set=set
ac_cv_env_MPICC_value=/usr/local/bin/mpicc
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_ac_pt_PKG_CONFIG=/usr/bin/pkg-config
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=/usr/local/bin/mpicc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /mnt/c/software/MrBayes/autotools/missing aclocal-1.15'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /mnt/c/software/MrBayes/autotools/missing autoconf'
AUTOHEADER='${SHELL} /mnt/c/software/MrBayes/autotools/missing autoheader'
AUTOMAKE='${SHELL} /mnt/c/software/MrBayes/autotools/missing automake-1.15'
AWK='gawk'
BEAGLE_CFLAGS=''
BEAGLE_LIBS=''
BIBTEX=''
BUILD_DOC_FALSE='#'
BUILD_DOC_TRUE=''
CC='/usr/local/bin/mpicc'
CCDEPMODE=''
CFLAGS='-O3 -DNDEBUG -std=c99 -pedantic '
CPP=''
CPPFLAGS=''
CPUEXT_FLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
HAVE_LATEXMK_FALSE=''
HAVE_LATEXMK_TRUE='#'
HAVE_LATEX_FALSE=''
HAVE_LATEX_TRUE='#'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LATEXMK=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /mnt/c/software/MrBayes/autotools/missing makeinfo'
MKDIR_P='/bin/mkdir -p'
MPICC='/usr/local/bin/mpicc'
OBJEXT=''
PACKAGE='mrbayes'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='MrBayes'
PACKAGE_STRING='MrBayes 3.2.7a'
PACKAGE_TARNAME='mrbayes'
PACKAGE_URL=''
PACKAGE_VERSION='3.2.7a'
PATH_SEPARATOR=':'
PDFLATEX=''
PKG_CONFIG='/usr/bin/pkg-config'
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
SIMD_FLAGS=''
STRIP=''
VERSION='3.2.7a'
ac_ct_CC='/usr/local/bin/mpicc'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /mnt/c/software/MrBayes/autotools/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "MrBayes"
#define PACKAGE_TARNAME "mrbayes"
#define PACKAGE_VERSION "3.2.7a"
#define PACKAGE_STRING "MrBayes 3.2.7a"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "mrbayes"
#define VERSION "3.2.7a"
#define HOST_TYPE "x86_64-unknown-linux-gnu"
#define HOST_CPU "x86_64"

configure: exit 77
```
THANKS!

**Comment by andkaha** [comment] 2020-02-09 12:57
The lines saying
```
/usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
```
indicate that MPI itself is not properly compiled and/or installed.  The library `libopen-pal.so.40` is a library that MPI is using, and it can't find it.

You should ideally install MPI from the package manager of your Unix, which makes sure that the MPI tools are installed appropriately.

**Comment by zhouzhendiao** [comment] 2020-02-09 15:08
> The lines saying
> 
> ```
> /usr/local/bin/mpicc: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
> ```
> 
> indicate that MPI itself is not properly compiled and/or installed. The library `libopen-pal.so.40` is a library that MPI is using, and it can't find it.
> 
> You should ideally install MPI from the package manager of your Unix, which makes sure that the MPI tools are installed appropriately.

Thanks!!!
