### ISSUE TITLE
Empty column in .p file with prset symdirihyperpr=fixed

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#58] opened 2018-05-23 09:09 UTC
Transferred from https://sourceforge.net/p/mrbayes/bugs/1657/

Created: 2018-04-06
Creator: Martin Smith

MrBayes 3.2.6 on Windows 10 is producing an additional header in the .p files (or an empty column, depending on how you look at it).

My feeling is that this is related to using the command

prset applyto=(1) symdirihyperpr=fixed(1.0);

This causes an error in command "Sump":

Expected 9 headers but found 10 headers

I've attached an example .p file and include the MrBayes block below.
I'd be happy to share the full matrix privately if that helps to reconstruct the error.

Comment (2018-04-11):
As a further observation, character 83 in the above matrix had four states (0, 1, 2, 3). Moving it from charset 1 to charset 2, such that it was not subject to the symdirihyperpr, meant that the pi_83 parameters did not need to be estimating, and all the columns were populated. Adding another character with three states (0, 1, 2) to charset 1 meant that three new columns were added to the pstat file, pi_66(0), pi_66(1), and pi_66(2). This leads me to suspect that the issue is that the m{1} column is not populated when some characters under the fixed symdidihyperpr have multiple states.

BEGIN MRBAYES;
set autoclose=yes nowarn=yes;
lset coding=variable rates=gamma;
prset brlenspr = unconstrained: gammadir(1, 0.326, 1, 1);
charset Neomorphic = 1 4 6 7 8 9 11 13 16 17 18 21 22 23 24 27 28 29 32 34 36 43 44 46 47 48 49 50 51 54 58 59 60 61 63 64 68 69 71 72 74 77 78 82 83 84 85 86 88 89 90 93 94 96; 
charset Transformational = 2 3 5 10 12 14 15 19 20 25 26 30 31 33 35 37 38 39 40 41 42 45 52 53 55 56 57 62 65 66 67 70 73 75 76 79 80 81 87 91 92 95 97 98;
partition chartype2 = 2: Neomorphic, Transformational;
set partition = chartype2;
unlink shape=(all) pinvar=(all);
prset applyto=(1) symdirihyperpr=fixed(1.0);
prset applyto=(1) ratepr=variable;
outgroup Dailyatia;
mcmc ngen=1000000 samplefreq=500 nruns=4 nchains=8 burninfrac=0.1;
sumt burninf=0.1; [fine]
sump burninf=0.1; [errors]
END;
[hyo.nex.run1.p.gz](https://github.com/NBISweden/MrBayes/files/2030313/hyo.nex.run1.p.gz)

**Comment by nylander** [comment] 2019-03-21 14:00
I can reproduce this bug (and more!) for mb.3.2.7 (Linux).

For now, this is the input required to reproduce:

Data file "data.nex":
```
#NEXUS
[Thu 21 Mar 2019 01:20:00 PM CET]
Begin Data;
    Dimensions Ntax=5 Nchar=28;
    Format Missing=? Gap=- Datatype=Standard;
    Matrix
        Apa 3333000303111331103130033011
        Bpa 0303000321233133303110033031
        Cpa 3333002311111131103330231211
        Dpa 3333030321231131103130013211
        Epa 0030302121131111120132203010
    ;
End;
```

Command file "mbblock.nex":
```
Begin Mrbayes;
    set seed=123456 swapseed=123456;
    set autoclose=yes nowarn=yes;
    exe data.nex;
    outgroup Apa;
    charset N = 1 3 5 7 9 11 13 15 17 19 21 23 25 27;
    charset T = 2 4 6 8 10 12 14 16 18 20 22 24 26 28;
    partition C = 2:N, T;
    set partition = C;
    prset applyto=(all) ratepr=variable;
    lset applyto=(all) coding=variable rates=gamma;
    prset applyto=(1) symdirihyperpr=fixed(1.0);
    unlink shape=(all) pinvar=(all);
    mcmc ngen=10000 nruns=1 nchains=1;
    sump;
End;
```

Commands:

```
$ mb mbblock.nex
```

## Comments

Any of the following variations produces wrong number of headers/columns in the \*.p file:
``` 
prset applyto=(1) symdirihyperpr=fixed(1.0);
prset applyto=(2) symdirihyperpr=fixed(1.0);
prset applyto=(1) symdirihyperpr=fixed(100.0);
```
More disturbingly, any of the following lines/combinations will result in a core dump:
```
prset applyto=(all) symdirihyperpr=fixed(1.0);
prset applyto=(all) symdirihyperpr=fixed(100.0);
prset applyto=(all) symdirihyperpr=exponential(1);
prset symdirihyperpr=uniform(0, 1);

prset applyto=(1) symdirihyperpr=uniform(0, 1);
prset applyto=(2) symdirihyperpr=uniform(0, 1);
```

**Comment by winni2k** [comment] 2020-07-02 07:05
I can confirm observing this behavior on my debian machine running `MrBayes 3.2.7 x86_64` (installed from conda) when running a standard model.

**Comment by winni2k** [comment] 2020-07-02 07:15
I apologize in advance for hijacking this thread, but does anyone know how the column names for the stationary distributions of the standard model are defined when setting `prset applyto=(1) symdirihyperpr=fixed(1.0);`? For example, in my .p file I get:
```
... pi_1(0)       pi_1(1)       pi_1(2)       pi_3(0)       pi_3(1) ...
```
Which transitions in the standard model do these columns refer to?

**Comment by ronquist** [comment] 2020-07-04 15:18
I now fixed the sampling of states when the symmetric beta / dirichlet prior is not fixed to infinity. There were two main issues; one was related simply to the printing, while the other caused problems when two partitions could share the same state frequency parameter, but the sampling of state frequencies for multistate characters (characters with more than two states) caused problems because of conflicts with the MrBayes computational machinery, which assumes that the sampling can be handled separately for the two partitions. A solution to this problem requires the introduction of one more parameter type in MrBayes, and I refrain from making such a change at this point. This constraint only causes problems if you want to sample the symmetric dirichlet variance parameter against a prior. If the prior on the variance parameter is fixed, there is no problem with the current setup.

As a reply to the last question from @winni2k , these substitution models are similar to the F81 model, that is, the reversible rates are all 1 and it is only the stationary state frequencies that determine the transition rates. In the example above, character 1 apparently has three states, and the sampled stationary frequencies of those states are in the columns pi_1(0), pi_1(1), and pi_1(2) for the three states 0, 1 and 2, respectively.

I will close this issue now and post a pull request for merging the code that fixes the issue, which is in branch/issue-58, into the develop branch.

**Closed by ronquist** 2020-07-04 15:18 UTC
Labels: bug

**Comment by winni2k** [comment] 2020-07-05 08:32
Thanks! I will do some more reading around the F81 model to see if I can understand this answer and open a new issue if I am still confused.
