### ISSUE TITLE
Beagle fail with serial but not mpi version

### ISSUE THREAD

**Issue by josephwb** [NBISweden/MrBayes#72] opened 2018-07-23 10:27 UTC
Serial version:
```
./mb


                            MrBayes pre-3.2.7 x86_64

                      (Bayesian Analysis of Phylogeny)

              Distributed under the GNU General Public License


               Type "help" or "help <command>" for information
                     on the commands that are available.

                   Type "about" for authorship and general
                       information about the program.


MrBayes > showbeagle

Unable to load CPU plugin!
Please check for proper libhmsbeagle installation.
   Available resources reported by beagle library:
   BEAGLE version: 3.0.2
```
MPI version:
```
./mb_mpi 


                            MrBayes pre-3.2.7 x86_64

                      (Bayesian Analysis of Phylogeny)

                             (Parallel version)
                         (1 processors available)

              Distributed under the GNU General Public License


               Type "help" or "help <command>" for information
                     on the commands that are available.

                   Type "about" for authorship and general
                       information about the program.


MrBayes > showbeagle

   Available resources reported by beagle library:
	Resource 0:
	Name: CPU
	Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE VECTOR_SSE THREADING_NONE

   BEAGLE version: 3.0.2
```
I get this same behaviour with the [non-github distributed code](http://nbisweden.github.io/MrBayes/download.html) (v3.2.6).

**Comment by josephwb** [comment] 2018-07-26 11:51
On a different machine with an older version of beagle (v2.1.2) things work:
```
./mb 


                            MrBayes pre-3.2.7 x86_64

                      (Bayesian Analysis of Phylogeny)

              Distributed under the GNU General Public License


               Type "help" or "help <command>" for information
                     on the commands that are available.

                   Type "about" for authorship and general
                       information about the program.


MrBayes > showbeagle

   Available resources reported by beagle library:
	Resource 0:
	Name: CPU
	Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE VECTOR_SSE THREADING_NONE

	Resource 1:
	Name: Quadro M4000
	Desc: Global memory (MB): 8124 | Clock speed (Ghz): 0.77 | Number of cores: 2496
	Flags: PROCESSOR_GPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE THREADING_NONE

   BEAGLE version: 2.1.2
```

**Comment by nylander** [comment] 2018-09-14 12:11
Dear josephwb,
Thank you for the report. We are currently looking at the possibility of incorporating full support for the latest version of libhmsbeagle into the development version of MrBayes. Obviously, we are not there yet, but the issue is of high priority.
Yours
Johan

**Comment by nylander** [comment] 2018-11-26 09:58
Hi,
`showbeagle` now locates resources for both serial and mpi version for the code in branch "feature/beagle3". This branch will hopefully soon be merged in to "develop" (and then "master" and released!)

**Comment by josephwb** [comment] 2018-11-26 10:02
Great. Thanks.

**Comment by nylander** [comment] 2019-03-21 11:29
Should now work off version 3.2.7 (branches master, develop). Plus/minus some potential issues (#100 ).
Closing.

**Closed by nylander** 2019-03-21 11:29 UTC
Labels: Beagle-related
