### ISSUE TITLE
Error in reading partitions file 

### ISSUE THREAD

**Issue by metagusano** [NBISweden/MrBayes#35] opened 2016-10-11 07:38 UTC
Hi!
During the tutorial in the "Partitioned Analysis" chapter, after writing the **cynmix-command.nex** as following:

```
#NEXUS
begin mrbayes;
   execute cynmix.nex;
   charset morphology = 1-166;
   charset COI = 167-1244;
   charset EF1a = 1245-1611;
   charset LWRh = 1612-2092;
   charset 28S = 2093-3246;
   partition favored = 5: morphology, COI, EF1a, LWRh, 28S;
   set partition = favored;
end;
```

I typed:

   `MrBayes > execute cynmix-command.nex`

An error message appears:

```
Could not find command "6"
      The error occurred when reading char. 1-1 on line 2
      in the file 'cynmix-command.nex'

   Returning execution to command line ...

   Error in command "Execute"
```

Only adding `set partition = favored` at the end of **cynmix.nex** would run the data file as expected, but never running it through cynmix-command.nex.

This is release 3.2.7

Regards

**Comment by nylander** [comment] 2018-07-10 16:50
Could not reproduce this error in v.3.2.7.
Note however, that running the above mentioned command file will throw another error, due to the fact that character partition names are attempted to be overwritten ("used again" - they are already defined in the cynmix.nex file!)

**Comment by nylander** [comment] 2019-03-21 10:28
closing

**Closed by nylander** 2019-03-21 10:28 UTC
Labels: wontfix
